"""REMOVE the UNIQUE from name column in user

Revision ID: a582257a7122
Revises: a245f114d34e
Create Date: 2025-06-11 21:17:32.909721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a582257a7122'
down_revision = 'a245f114d34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
